### Exercise 1.1: The interpreter

In [1]:
3+1

4

In [2]:
3*3

9

In [3]:
2 ** 3

8

In [4]:
"Hello, world!"

'Hello, world!'

It runs every code piece correcly. There is no errors.

### Exercise 1.2: Scripts

If we ran codes that given at above, it gives error. We can fix this by:

In [15]:
print(3+1)
print(3*3)
print(2 ** 3)
"Hello, world!"

4
9
8


'Hello, world!'

### Exercise 1.3: More Interpreter

In [11]:
'py' + 'thon'

'python'

'py' + 'thon' gives output as 'python'. It concanates strings.

In [12]:
'py'*3 + 'ton'

'pypypyton'

'py' * 3 + 'ton' gives output as 'pypypyton'. It concats 'py' * x times. And adds 'ton'.

In [14]:
'py'- 'py'

TypeError: unsupported operand type(s) for -: 'str' and 'str'

It returns TypeError: unsupported operand type(s) for -: 'str' and 'str'. 

Because '-' operand can not be applied to strings.

In [17]:
'3'+3

TypeError: can only concatenate str (not "int") to str

It returns TypeError: can only concatenate str (not "int") to str. 

In [20]:
3 * '3'

'333'

It returns '333', concanates '3' by *x times

In [21]:
a

NameError: name 'a' is not defined

It returns NameError, because a is not defined.

In [22]:
a = 3

In [23]:
a

3

Now it returns 3, because we have declared a as 3 at above.

### Exercise 1.4: Booleans

In [25]:
1 == 1

True

Returns true.

In [27]:
1 == True

True

Returns true.Because true is equal to 1 in binary.

In [28]:
0 == True

False

Returns false because of the same reason at above.

In [29]:
0 == False

True

Returns true.Because false is equal to 0 in binary.

In [30]:
3 == 1 * 3

True

Returns true.

In [29]:
0 == False

True

Returns true.Because false is equal to 0 in binary.

In [32]:
(3 == 1) * 3

0

Returns 0.Because 3 is not equal to 1 thus, first expression comes 0. And any number multiplication by 0 is 0.

In [34]:
(3 == 3) * 4 + 3 == 1

False

Returns false.(true) = 1, and 1 * 4 = 4, 4 +3 =7 and 7 == 1 equals false.

In [35]:
3**5 >= 4**4

False

Returns false.Because 3ˆ5 is not equal or greater than 4ˆ4

### Exercise 1.5: Integers

In [36]:
5 / 3

1.6666666666666667

It returns 5 division by 3.

In [38]:
5 % 3

2

It returns reminder of dividing 5 by 3.

In [40]:
5.0 / 3

1.6666666666666667

It returns 5 division by 3. Types are not important.

In [41]:
5 / 3.0

1.6666666666666667

It returns 5 division by 3. Types are not important.

In [42]:
5.2 % 3

2.2

It returns reminder of dividing 5.2 by 3.

In [43]:
2001 ** 200

1775896810483121914350934797871501063452843428843794422323202530887281536545210629921129898113201749875234297340507804201761453596034016264189501186924066128377025843892373608427790859511135990682732202975330824797118808624727351608183194154557208730494440110429635650057431833674286462463508755276302896154336475782768613964332764108132533925570342220340698973761380541294970139762186212823359128790706292900765512137078550033912252338262922477518858757114840012576514724742388124595061301502222934806074032688691170880996881967426442947828261057852871032366879179996122216385870273020506079240103910728766397733398071775041745854959302025036249707279600400001

It returns 2001ˆ200. (2001 * 2001 * 2001 *....* (200 times)

### Exercise 1.6: Floats

In [44]:
2000.3 ** 200

OverflowError: (34, 'Result too large')

It returns OverflowError: (34, 'Result too large'). Python floats are neither arbitary precision nor of unlimited size. When k = 349, 16.** k is much too large - thats almost 2^1400. Fortunately, the decimal library allows arbitrary precision and can handle the size. We can use decimal library.

In [46]:
1.0 + 1.0 - 1.0

1.0

It returns 1.0. 

In [47]:
1.0 + 1.0e20 - 1.0e20

0.0

It returns 0.0. Because, 1.0e20 is big float and if we substract itself and add 1.0 then it rounds the nearest point and it was 0.0.

### Exercise 1.7: Variables

In [72]:
name = 'Nida Dinc'

In [73]:
print('Hello,', name,'!')

Hello, Nida Dinc !


In [74]:
name = 'John Doe'

In [75]:
print('Hello,', name,'!')

Hello, John Doe !


### Exercise 1.8: Type casting

In [76]:
float(123)

123.0

It returns 123.0, it casts integer to float

In [78]:
float('123')

123.0

It returns 123.0, it casts string to float

In [81]:
float('123.23')

123.23

It returns 123.23, it casts float to float

In [82]:
int(123.23)

123

It returns 123, it casts float to int

In [88]:
int('123.23')

ValueError: invalid literal for int() with base 10: '123.23'

It returns ValueError, it can not string to int because string looks like a float. If we give int('123'), it can cast string to int.

In [89]:
int(float('123.23'))

123

It returns 123, it casts string to float and after it casts float to int.

In [90]:
str(12)

'12'

It returns '12', it casts int to string

In [91]:
str(12.2)

'12.2'

It returns '12.2', it casts float to string

In [98]:
bool('a')

True

It returns true.Because a string is truthy, if it is non-empty. Only empty strings convert to False.

In [95]:
bool(0)

False

It returns false, because 0 equals false in binary

In [96]:
bool(0.1)

True

It returns true, because 0.1 is not equal to 0 thus, is not false.

## 2. Control flow

### Exercise 2.1: Range

In [1]:
range(5)

range(0, 5)

In [11]:
for i in range(5):
    print()

In [4]:
type(range(5))

range

### Exercise 2.2: For loops

- (a) Print the numbers 0 to 100

In [9]:
for i in range(100):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


- (b) Print the numbers 0 to 100 that are divisible by 7

In [12]:
for i in range(100):
    if i % 7 == 0:
        print(i)

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


- (c) Print the numbers 1 to 100 that are divisible by 5 but not by 3

In [25]:
for i in range(1,100):
    if i % 5 == 0 and i % 3 != 0:
            print(i)

5
10
20
25
35
40
50
55
65
70
80
85
95


- (d) Print for each of the numbers x = 2, . . . 20, all numbers that divide x, excluding 1 and x. Hence, for 18, it should print 2 3 6 9.

In [29]:
x = 18
for i in range(1,x):
    if x % i == 0 and i != 1:
            print(i)

2
3
6
9


### Exercise 2.3: Simple while loops

- (a) Print the numbers 0 to 100

In [33]:
i = 0
while i < 100:
    print(i)
    i+=1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


- (b) Print the numbers 0 to 100 that are divisible by 7

In [36]:
i = 0 
while i <100:
    if i % 7 == 0:
        print(i)
    i += 1

0
7
14
21
28
35
42
49
56
63
70
77
84
91
98


### Exercise 2.5: While Loops

- Use a while loop to find the first 20 numbers that are divisible by 5, 7 and 11, and print them Hint: store the number found so far in a variable.

In [38]:
counter = 0 
x = 0
while counter < 20:
    if x % 5 == 0 and x % 7 == 0 and x % 11 == 0:
        print(x)
        counter += 1
    x += 1

0
385
770
1155
1540
1925
2310
2695
3080
3465
3850
4235
4620
5005
5390
5775
6160
6545
6930
7315


### Exercise 2.6: More while loops

- The smallest number that is divisible by 2, 3 and 4 is 12. Find the smallest number that is divisible by all integers between 1 and 10.

In [59]:
x = 1
while 1:
    if x % (1*2*3*4*5*6*7*8*9) == 0:
        print(x)
        break
    x += 1

362880


### Exercise 2.7: Collatz sequence

- Print the Collatz sequence starting at x0 = 103.

In [68]:
x = 103
while x != 1:
    if x % 2 == 0:
        x = x/2
    else:
        x = 3*x+1
    print(int(x), end=" ")
    

310 155 466 233 700 350 175 526 263 790 395 1186 593 1780 890 445 1336 668 334 167 502 251 754 377 1132 566 283 850 425 1276 638 319 958 479 1438 719 2158 1079 3238 1619 4858 2429 7288 3644 1822 911 2734 1367 4102 2051 6154 3077 9232 4616 2308 1154 577 1732 866 433 1300 650 325 976 488 244 122 61 184 92 46 23 70 35 106 53 160 80 40 20 10 5 16 8 4 2 1 

## 3. Functions

### Exercise 3.1: Hello

- (a) Write a function hello_world that prints ’Hello, world!’

In [77]:
def hello():
  print("Hello, world!")

hello()

Hello, world!


- (b) Write a function hello_name(name) that prints ’Hello, name!’ where name is a string.

In [79]:
def hello(name):
  print("Hello,", name, "!")

hello("Nida")

Hello, Nida !


- (c) Explain the difference between the print and return keywords. What would change if instead of print you would use return?

Print keyword prints to screen but return keyword returns something. So, we can use print in everywhere, but we can not use return in everywhere. We can only use it in functions. If I change print to return statement, Its not necessary to call function into print like print(hello("Nida")) in like these interpreters.

### Exercise 3.2: Polynomial

- Write a function that evaluates the polynomial 3x2 − x + 2.

In [85]:
def polynomial(x):
    return 3*x **2 - x + 2

polynomial(3)

26

### Exercise 3.3: Maximum

In [90]:
def my_max(x,y):
    if x > y:
        return x
    return y

my_max(39,5)

39

### Exercise 3.4: Primes

- (a) Write a function is_prime(n) that returns True only if n is prime.

In [159]:
from math import sqrt

def is_prime(num):
     if num > 1:
        for i in range(2, num):
            if (num % i) == 0:
                return False
        else:
            return True
        num += 1
        
is_prime(29)

True

- (b) Note that apart from 2 and 3, all primes are of the form 6k ± 1 (though not all numbers of the form 6k ± 1 are prime of course). Using this, we can improve the computation time by a factor 3. Update your function to use this.


In [130]:
def is_prime(n):
    if (n <= 1):
        return False
 
    if ((n - 1) % 6 == 0) or ((n + 1) % 6 == 0) or n == 2 or n == 3  :
        return True
    
    return False

is_prime(41)

True

- (c) Write a function that returns all primes up to n.

In [146]:
def all_primes(n):
    num = 1
    while num < n:
        if num > 1:
            for i in range(2, num):
                if (num % i) == 0:
                    break
            else:
                print(num) 
        num += 1
all_primes(124)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
101
103
107
109
113


- (d) Write a function that returns the first n primes.

In [164]:
def all_primes(n):
    num = 1
    count = 0
    while count < n:
        if num > 1:
            for i in range(2, num):
                if (num % i) == 0:
                    break
            else:
                print(num) 
                count += 1
        num += 1
        
all_primes(6)

2
3
5
7
11
13


### Exercise 3.5: Root finding

Suppose f is a continuous function and f(a) < 0 and f(b) > 0 for some known a and b. For simplicity, assume a < b. Then, there must exist some c such that f(c) = 0.
- (a) Write a function root(f, a, b) that takes a function f and two floats a and b and returns the root c. Hint: check the sign at the midpoint of the interval.

In [ ]:
def root(f,a,b):
    d = (b**2) - (4*a*c)
        if d < 0:
            return []

        if d > 0:
            square_root_d = math.sqrt(d)
            t1 = (-b + square_root_d) / (2 * a)
            t2 = (-b - square_root_d) / (2 * a)
            if t1 > 0:
                if t2 > 0:
                    if t1 < t2:
                        return [t1, t2]
                    return [t2, t1]
                return [t1]
            elif t2 > 0:
                return [t2]
            else:
                return []
        else:
            t = -b / (2*a)
            if t > 0:
                return [t]
            return []